website/app/urls.py
from django.contrib import admin
from django.urls import include, path
from controllers.usuarios.models import *
from controllers.usuarios.views import *
from controllers.clientes.models import *
from controllers.clientes.views import *
from controllers.iscas.models import *
from controllers.login.views import *
from controllers.rastreamentos.models import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    
    path(r"",HomePage,name="home"),
    
    path(r"login/",LoginPage, name="login"),
    
    path(r"logout/",LogoutPage, name="logout"),
    
    path(r'usuarios/', include('controllers.usuarios.urls')),
    
    path(r'usuarios_operacoes/', include('controllers.usuarios_operacoes.urls')),
    
    path(r'iscas/', include('controllers.iscas.urls')),
    
    path(r'rastreamentos/', include('controllers.rastreamentos.urls')),
    
    path(r'solicitacoes/', include('controllers.solicitacoes.urls')),
    
    path(r'checklists/', include('controllers.checklists.urls')),
    
    path(r'clientes/', include('controllers.clientes.urls')),
    
    path(r'operacoes/', include('controllers.operacoes.urls')),
    
    path(r'locais/', include('controllers.locais.urls')),
    
    path(r'locais_clientes/', include('controllers.locais_clientes.urls')),
    
    path(r'fornecedores/', include('controllers.fornecedores.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/controllers/solicitacoes/urls.py
from django.urls import path
from .models import *
from .views import *

app_name = 'solicitacoes'

urlpatterns = [
    path(r"index" ,index ,name="index"),
    path(r"buscar", buscar, name="buscar"),
    path(r"buscar_removidos" ,buscar_removidos ,name="buscar_removidos"),
    path(r"buscar_by_Id/<int:id>/", buscar_by_Id, name="buscar_by_Id"),
    path(r"cadastrar_range", cadastrar_range, name="cadastrar_range"),
    path(r"deletar/<int:id>/", deletar, name="deletar"),
    path(r"atualizar_checkout/<int:id>/", atualizar_checkout, name="atualizar_checkout"),
    path(r"atualizar_checkin/<int:id>/", atualizar_checkin, name="atualizar_checkin")
]

website/templates/listar/cliente_list.html
<section class="py-2 my-3 px-lg-2 fundo-white">
    <div class="table-responsive mt-1 py-2 px-3">
        <table class="table tabela-clientes align-middle table-borderless">
            <thead>
                <tr class="align-bottom">
                    <th data-orderable="false">Ativo</th>
                    <th>Codigo</th>
                    <th>Razão Social</th>
                    <th>CNPJ</th>
                    <th>Email</th>
                    <th>CEP</th>
                    <th>Data Criado</th>
                    <th data-orderable="false">Ações</th>
                </tr>
            </thead>
            <tbody>
                {% if clientes_list %}
                    {% for cliente in clientes_list %}
                        <tr>
                            <td>
                                <button class="figure small pe-1">
                                    <i class="fa-solid fa-circle" style="color: {% if cliente.ativo %}rgb(32, 218, 100);{% else %}#ba2525;{% endif %}"></i>
                                </button>
                            </td>
                            <td>{{cliente.id | default:"N/A"}}</td>
                            <td>{{cliente.razao_social | default:"N/A"}}</td>
                            <td>{{cliente.cnpj | default:"N/A"}}</td>
                            <td>{{cliente.email | default:"N/A"}}</td>
                            <td>{{cliente.cep | default:"N/A"}}</td>
                            <td>{{cliente.data_criado | date:"d/m/Y" | default:"N/A" }}</td>
                            <td>
                                <button class="icone medium" data-bs-placement="right" title="Editar clientes" onclick="modal_editar_clientes({{ cliente.id }})" > 
                                    <i class="fa-solid fa-pen-to-square" style="color: #1968a4;"></i>
                                </button>
                                <button class="icone medium" data-bs-placement="right" title="Excluir clientes" onclick="modal_excluir_clientes({{ cliente.id }})" >
                                    <i class="fa-solid fa-trash" style="color: #df3030;"></i>
                                </button>
                            </td>
                        </tr>
                    {% endfor %}
                {% endif %}
            </tbody>
        </table>
    </div>
</section>

website/templates/listar/fornecedor_list.html
<section class="py-2 my-3 px-lg-2 fundo-white">
    <div class="table-responsive mt-1 py-2 px-3">
        <table class="table tabela-fornecedores align-middle table-borderless">
            <thead>
                <tr class="align-bottom">
                    <th data-orderable="false">Ativo</th>
                    <th>Codigo</th>
                    <th>Nome</th>
                    <th>Email</th>
                    <th>Telefone</th>
                    <th>Data Criado</th>
                    <th data-orderable="false">Ações</th>
                </tr>
            </thead>
            <tbody>
                {% if fornecedores_list %}
                    {% for fornecedor in fornecedores_list %}
                        <tr>
                            <td>
                                <button class="figure small pe-1">
                                    <i class="fa-solid fa-circle" style="color: {% if fornecedor.ativo %}rgb(32, 218, 100);{% else %}#ba2525;{% endif %}"></i>
                                </button>
                            </td>
                            <td>{{fornecedor.id | default:"N/A"}}</td>
                            <td>{{fornecedor.nome | default:"N/A"}}</td>
                            <td>{{fornecedor.email | default:"N/A"}}</td>
                            <td>{{fornecedor.telefone | default:"N/A"}}</td>
                            <td>{{fornecedor.data_criado | date:"d/m/Y" | default:"N/A" }}</td>
                            <td>
                                <button class="icone medium" data-bs-placement="right" title="Editar fornecedores" onclick="modal_editar_fornecedores({{ fornecedor.id }})" > 
                                    <i class="fa-solid fa-pen-to-square" style="color: #1968a4;"></i>
                                </button>
                                <button class="icone medium" data-bs-placement="right" title="Excluir fornecedores" onclick="modal_excluir_fornecedores({{ fornecedor.id }})" >
                                    <i class="fa-solid fa-trash" style="color: #df3030;"></i>
                                </button>
                            </td>
                        </tr>
                    {% endfor %}
                {% endif %}
            </tbody>
        </table>
    </div>
</section>

website/templates/listar/isca_list.html
<section class="py-2 my-3 px-lg-2 fundo-white">
    <div class="table-responsive mt-1 py-2 px-3">
        <table class="table tabela-iscas align-middle table-borderless">
            <thead>
                <tr class="align-bottom">
                    <th data-orderable="false"></th>
                    <th>Numero</th>
                    <th>Fornecedor</th>
                    <th>Comunicação</th>
                    <th>Modelo</th>
                    <th>Status</th>
                    <th>local</th>
                    <th>Cliente</th>
                    <th>Operação</th>
                    <th>Data Criado</th>
                    <th data-orderable="false">Ações</th>
                </tr>
            </thead>
            <tbody>
                {% if iscas_list %}
                    {% for isca in iscas_list %}
                        <tr>
                            <td>
                                <input type="checkbox" name="checkbox-isca" value="{{isca.id}}">
                            </td>
                            <td>
                                <button class="figure pe-1">
                                    <i class="fa-solid fa-tower-broadcast" style="color: {% if isca.ativo %}#2caf46;{% else %}#ba2525;{% endif %}"></i>
                                </button>
                                <button class="text-reduzido">
                                    {{isca.numero_isca | default:"N/A"}}
                                </button>
                            </td>
                            <td>{{isca.fornecedor.nome | default:"N/A"}}</td>
                            <td>{{isca.comunicacao | default:"N/A"}}</td>
                            <td>{{isca.modelo | default:"N/A"}}</td>
                            <td>
                                <button class="figure small">
                                    <i class="fa-solid fa-circle" style="color: {% if isca.status == "Almoxarifado" %}rgb(32, 218, 100);{% else %}goldenrod;{% endif %}"></i>
                                </button>
                                <button class="text status">
                                    {{isca.status | default:"N/A"}}
                                </button>
                            </td>
                            <td>{{isca.local_cliente.local.nome | default:"N/A"}}</td>
                            <td>{{isca.operacao.cliente.razao_social | default:"N/A"}}</td>
                            <td>{{isca.operacao.nome | default:"N/A"}}</td>
                            <td>{{isca.data_criado | date:"d/m/Y" | default:"N/A"}}</td>
                            <td>
                                <button class="icone medium" data-bs-placement="right" title="Editar isca" onclick="modal_editar_iscas({{ isca.id }})" > 
                                    <i class="fa-solid fa-pen-to-square" style="color: #1968a4;"></i>
                                </button>
                                <button class="icone medium" data-bs-placement="right" title="Excluir isca" onclick="modal_excluir_iscas({{ isca.id }})" >
                                    <i class="fa-solid fa-trash" style="color: #df3030;"></i>
                                </button>
                            </td>
                        </tr>
                    {% endfor %}
                {% endif %}
            </tbody>
        </table>
    </div>
</section>

website/templates/listar/local_list.html
<section class="py-2 my-3 px-lg-2 fundo-white">
    <div class="table-responsive mt-1 py-2 px-3">
        <table class="table tabela-locais align-middle table-borderless">
            <thead>
                <tr class="align-bottom">
                    <th data-orderable="false">Ativo</th>
                    <th>Codigo</th>
                    <th>Nome</th>
                    <th>CEP</th>
                    <th>Estado UF</th>
                    <th>Cidade</th>
                    <th>Data Criado</th>
                    <th data-orderable="false">Ações</th>
                </tr>
            </thead>
            <tbody>
                {% if locais_list %}
                    {% for local in locais_list %}
                        <tr>
                            <td>
                                <button class="figure small pe-1">
                                    <i class="fa-solid fa-circle" style="color: {% if local.ativo %}rgb(32, 218, 100);{% else %}#ba2525;{% endif %}"></i>
                                </button>
                            </td>
                            <td>{{local.id | default:"N/A"}}</td>
                            <td>{{local.nome | default:"N/A"}}</td>
                            <td>{{local.cep | default:"N/A"}}</td>
                            <td>{{local.estado_uf | default:"N/A"}}</td>
                            <td>{{local.cidade | default:"N/A"}}</td>
                            <td>{{local.data_criado | date:"d/m/Y" | default:"N/A" }}</td>
                            <td>
                                <button class="icone medium" data-bs-placement="right" title="Editar locais" onclick="modal_editar_locais({{ local.id }})" > 
                                    <i class="fa-solid fa-pen-to-square" style="color: #1968a4;"></i>
                                </button>
                                <button class="icone medium" data-bs-placement="right" title="Excluir locais" onclick="modal_excluir_locais({{ local.id }})" >
                                    <i class="fa-solid fa-trash" style="color: #df3030;"></i>
                                </button>
                            </td>
                        </tr>
                    {% endfor %}
                {% endif %}
            </tbody>
        </table>
    </div>
</section>

website/templates/listar/rastreamento_list.html
<section class="py-2 my-3 px-lg-2 fundo-white">
    <div class="table-responsive mt-1 py-2 px-3">
        <table class="table tabela-rastreamentos align-middle table-borderless" >
            <thead>
                <tr class="align-bottom">
                    <th data-orderable="false"></th>
                    <th>Numero SM</th>
                    <th>Nota Fiscal</th>
                    <th>Numero Isca</th>
                    <th>Rota Inserção</th>
                    <th>Rota Maior Valor</th>
                    <th>Resultado</th>
                    <th>Valor SM</th>
                    <th>Volume</th>
                    <th>Motorista</th>
                    <th>Placa</th>
                    <th>Manifesto</th>
                    <th>Data Implantada</th>
                    <th>Data Saida</th>
                </tr>
            </thead>
            <tbody>
                {% if rastreamentos_list %}
                    {% for rastreamento in rastreamentos_list %}
                        <tr>
                            <td >
                                <input type="checkbox" id="checkbox-rastreamento" name="checkbox-rastreamento" value="{{rastreamento.id}}">
                            </td>
                            <td>
                                <button class="figure pe-1">
                                    <i class="fa-solid fa-truck" style="color: {% if rastreamento.ativo %}#2caf46;{% else %}#ba2525;{% endif %}"></i>
                                </button>
                                <button class="text-reduzido">
                                    {{rastreamento.sm | default:"N/A"}}
                                </button>
                            </td>
                            <td>{{rastreamento.nota_fiscal | default:"N/A"}}</td>
                            <td>
                                <button class="text-reduzido">
                                    {{rastreamento.isca.numero_isca | default:"N/A"}}
                                </button>
                            </td>
                            <td>{{rastreamento.rota_insercao | default:"N/A"}}</td>
                            <td>{{rastreamento.rota_maior_valor | default:"N/A"}}</td>
                            <td>
                                <button class="figure small pe-1">
                                    <i class="fa-solid fa-circle" style="color: {% if rastreamento.resultado == "Em viagem" %}rgb(32, 218, 100);{% elif rastreamento.resultado == "Implantada" %}goldenrod;{% else %}#ba2525;{% endif %}"></i>
                                </button>
                                <button class="text status ps-0">
                                    {{rastreamento.resultado | default:"N/A"}}
                                </button>
                            </td>
                            <td>R$ {{rastreamento.valor_sm | default:"N/A"}}</td>
                            <td>{{rastreamento.volume | default:"N/A"}}</td>
                            <td>{{rastreamento.motorista | default:"N/A"}}</td>
                            <td>{{rastreamento.placa | default:"N/A" }}</td>
                            <td>{{rastreamento.manifesto | default:"N/A"}}</td>
                            <td>{{rastreamento.data_implantacao | date:"d/m/Y" | default:"N/A" }}</td>
                            <td>{{rastreamento.data_saida | date:"d/m/Y" | default:"N/A" }}</td>
                        </tr>
                    {% endfor %}
                {% endif %}
            </tbody>
        </table>
    </div>
</section>

website/templates/listar/solicitacao_list.html
<section class="py-2 my-3 px-lg-2 fundo-white">
    <div class="table-responsive mt-1 py-2 px-3">
        <table class="table tabela-solicitacao align-middle table-borderless" >
            <thead>
                <tr class="align-bottom">
                    <th data-orderable="false">Ativo</th>
                    <th>Codigo</th>
                    <th>Numero Isca</th>
                    <th>Checkin</th>
                    <th>Checkout</th>
                    <th>Implantação</th>
                    <th>Data Criado</th>
                    <th data-orderable="false">Ações</th>
                </tr>
            </thead>
            <tbody>
                {% if solicitacoes_list %}
                    {% for solicitacao in solicitacoes_list %}
                        <tr>
                            <td>
                                <button class="figure small pe-1">
                                    <i class="fa-solid fa-circle" style="color: {% if solicitacao.ativo %}rgb(32, 218, 100);{% else %}#ba2525;{% endif %}"></i>
                                </button>
                            </td>
                            <td>{{solicitacao.id | default:"N/A"}}</td> 
                            <td>
                                <button class="text-reduzido">
                                    {{solicitacao.isca.numero_isca | default:"N/A"}}
                                </button>
                            </td>
                            <td>
                                <button class="figure"> 
                                    <i class="fa-regular fa-clipboard" style="color: {% if solicitacao.checkin == "Checkin Pendente" %}goldenrod !important;{% elif solicitacao.checkin == "Checkin Aprovado" %}#58ca7e;{% else %}rgb(218, 44, 32)!important;{% endif %}"></i>
                                </button>
                                <button class="text checkin-solicitacao"> 
                                    {{solicitacao.checkin | default:"N/A"}}
                                </button>
                                {% if solicitacao.checkin == "Checkin Reprovado" %}
                                    <button type="submit" class="text rotate" > 
                                        <a href="{% url 'solicitacoes:atualizar_checkin' id=solicitacao.id %}" data-bs-toggle="tooltip" data-bs-placement="right" title="Clique aqui para realizar o checkin novamente">
                                            <i class="fa-solid fa-rotate"> </i> 
                                        </a>
                                    </button>
                                {% endif %}
                            </td>
                            <td>
                                <button class="figure"> 
                                    <i class="fa-solid fa-clipboard" style="color: {% if solicitacao.checkout == "Checkout Aprovado" %}#58ca7e;{% elif solicitacao.checkout == "Checkout Reprovado" %}rgb(218, 44, 32);{% else %}goldenrod;{% endif %}"></i>
                                </button>
                                <button class="text checkout-solicitacao"> 
                                    {{solicitacao.checkout | default:"N/A"}}
                                </button>
                            </td>
                            <td>
                                <button class="text {% if solicitacao.implantacao == "Pendente" %}marca-pendente{% else %}marca-aprovada{% endif %}">
                                    {{ solicitacao.implantacao | default:"N/A" }}
                                </button>
                            </td>
                            <td>{{ solicitacao.data_criado | date:"d/m/Y" | default:"N/A" }}</td>
                            <td>
                                <button class="icone medium px-3" data-bs-toggle="dropdown"  data-bs-auto-close="outside" aria-expanded="false" data-bs-placement="right" title="Mais Ações">
                                    <i class="fa-solid fa-ellipsis-vertical" style="color:#1968a4;"></i>
                                </button>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a class="dropdown-item d-flex justify-content-between align-items-center {% if solicitacao.checkin != "Checkin Pendente" %}desativado{% endif %}" {% if solicitacao.checkin == "Checkin Pendente" %}onclick="open_modal_checkin({{solicitacao.id}})"{% else %}onclick="bloqueio_modal()"{% endif %} >
                                            <span>Checkin</span>
                                            <span><i class="fa-regular fa-clipboard me-1"></i><span>
                                        </a>    
                                    </li>
                                    <li>
                                        <a class="dropdown-item d-flex justify-content-between align-items-center {% if solicitacao.checkout != "Checkout Pendente" %}desativado{% endif %}" {% if solicitacao.checkout == "Checkout Pendente" %}onclick="open_modal_checkout({{solicitacao.id}})"{% else %}onclick="bloqueio_modal()"{% endif %} >
                                            <span>Checkout</span>
                                            <span><i class="fa-solid fa-clipboard me-1"></i><span>
                                        </a>    
                                    </li>
                                    <li>
                                        <a class="dropdown-item d-flex justify-content-between align-items-center" onclick="verificar_implantacao({{solicitacao.id}}, '{{solicitacao.isca.numero_isca}}',{{solicitacao.isca.id}})" >
                                            <span>Implantação</span>
                                            <span><i class="fa-solid fa-box me-1"></i><span>
                                        </a>    
                                    </li>
                                    <li>
                                        <a class="dropdown-item d-flex justify-content-between align-items-center {% if solicitacao.implantacao == "Pendente" or solicitacao.viagem == "Iniciada" %}desativado{% endif %}" onclick="verificar_inicio_sm({{solicitacao.id}})" >
                                            <span>Iniciar</span>
                                            <span><i class="fa-solid fa-truck me-0"></i><span>
                                        </a>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                    {% endfor %}
                {% endif %}
            </tbody>
        </table>
    </div>
</section>

website/templates/listar/usuario_list.html
<section class="py-2 my-3 px-lg-2 fundo-white">
    <div class="table-responsive mt-1 py-2 px-3">
        <table class="table tabela-usuarios align-middle table-borderless">
            <thead>
                <tr class="align-bottom">
                    <th>Codigo</th>
                    <th>Nome</th>
                    <th>Nivel de Acesso</th>
                    <th>Email</th>
                    <th>Telefone</th>
                    <th>Data Criado</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                {% if usuarios_list %}
                    {% for usuario in usuarios_list %}
                        <tr>
                            <td scope="col">{{usuario.id | default:"N/A"}}</td>
                            <td scope="col">{{usuario.user.username | default:"N/A"}}</td>
                            <td scope="col">{{usuario.roles | default:"N/A"}}</td>
                            <td scope="col">{{usuario.email | default:"N/A"}}</td>
                            <td scope="col">{{usuario.telefone | default:"N/A"}}</td>
                            <td scope="col">{{usuario.data_criado | date:"d/m/Y" | default:"N/A" }}</td>
                            <td>
                                <button class="icone medium" data-bs-placement="right" title="Editar usuarios" onclick="modal_editar_usuarios({{ usuario.id }})" > 
                                    <i class="fa-solid fa-pen-to-square" style="color: #1968a4;"></i>
                                </button>
                                <button class="icone medium" data-bs-placement="right" title="Excluir usuarios" onclick="modal_excluir_usuarios({{ usuario.id }})" >
                                    <i class="fa-solid fa-trash" style="color: #df3030;"></i>
                                </button>
                            </td>
                        </tr>
                    {% endfor %}
                {% endif %}
            </tbody>
        </table>
    </div>
</section>