website/app/urls.py
from django.contrib import admin
from django.urls import include, path
from controllers.usuarios.models import *
from controllers.usuarios.views import *
from controllers.clientes.models import *
from controllers.clientes.views import *
from controllers.iscas.models import *
from controllers.login.views import *
from controllers.rastreamentos.models import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    
    path(r"",HomePage,name="home"),
    
    path(r"login/",LoginPage, name="login"),
    
    path(r"logout/",LogoutPage, name="logout"),
    
    path(r'usuarios/', include('controllers.usuarios.urls')),
    
    path(r'usuarios_operacoes/', include('controllers.usuarios_operacoes.urls')),
    
    path(r'iscas/', include('controllers.iscas.urls')),
    
    path(r'rastreamentos/', include('controllers.rastreamentos.urls')),
    
    path(r'solicitacoes/', include('controllers.solicitacoes.urls')),
    
    path(r'checklists/', include('controllers.checklists.urls')),
    
    path(r'clientes/', include('controllers.clientes.urls')),
    
    path(r'operacoes/', include('controllers.operacoes.urls')),
    
    path(r'locais/', include('controllers.locais.urls')),
    
    path(r'locais_clientes/', include('controllers.locais_clientes.urls')),
    
    path(r'fornecedores/', include('controllers.fornecedores.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/controllers/clientes/urls.py
from django.urls import path
from .models import *
from .views import *

app_name = 'clientes'

urlpatterns = [
    path(r"index", index, name="index"),
    path(r"buscar", buscar, name="buscar"),
    path(r"buscar_removidos" ,buscar_removidos ,name="buscar_removidos"),
    path(r"cadastrar", cadastrar, name="cadastrar"),
    path(r"atualizar/<int:id>/", atualizar, name="atualizar"),
    path(r"deletar/<int:id>/", deletar, name="deletar"),
    path(r"buscar_by_Id/<int:id>/", buscar_by_Id, name="buscar_by_Id")
]

website/controllers/iscas/urls.py
from django.urls import path
from controllers.iscas.models import *
from controllers.iscas.views import *

app_name = 'iscas'

urlpatterns = [
    path(r"index" ,index ,name="index"),
    path(r"buscar" ,buscar ,name="buscar"),
    path(r"buscar_removidos" ,buscar_removidos ,name="buscar_removidos"),
    path(r"cadastrar", cadastrar, name="cadastrar"),
    path(r"atualizar/<int:id>/", atualizar, name="atualizar"),
    path(r"deletar/<int:id>/", deletar, name="deletar"),
    path(r"buscar_by_Id/<int:id>/", buscar_by_Id, name="buscar_by_Id"),
    path(r"leitor_qrcode", leitor_qrcode, name="leitor_qrcode"),
]

website/controllers/locais/urls.py
from django.urls import path
from .models import *
from .views import *

app_name = 'locais'

urlpatterns = [
    path(r"index" ,index ,name="index"),
    path(r"buscar" ,buscar ,name="buscar"),
    path(r"buscar_removidos" ,buscar_removidos ,name="buscar_removidos"),
    path(r"cadastrar", cadastrar, name="cadastrar"),
    path(r"atualizar/<int:id>/", atualizar, name="atualizar"),
    path(r"deletar/<int:id>/", deletar, name="deletar"),
    path(r"buscar_by_Id/<int:id>/", buscar_by_Id, name="buscar_by_Id")
]

website/controllers/usuarios/urls.py
from django.urls import path
from .models import *
from .views import *

app_name = 'usuarios'

urlpatterns = [
    path(r"index" ,index ,name="index"),
    path(r"buscar", buscar, name="buscar"),
    path(r"cadastrar", cadastrar, name="cadastrar"),
    path(r"atualizar/<int:id>/", atualizar, name="atualizar"),
    path(r"deletar/<int:id>/", deletar, name="deletar"),
    path(r"buscar_by_Id/<int:id/", buscar_by_Id, name="buscar_by_Id")
]

website/templates/bases/adicionar_cliente_base.html
{% extends 'bases/modal_base.html' %}

{% block modal_header %}
    
    <h5 class="modal-title">Escoha o cliente para ser adicionado</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>

{% endblock %}

{% block modal_body %}

    <div class="modal-body form-group py-3">
        {% csrf_token %}
        <div class="my-3">
            <label for="cliente">Cliente</label><small style="color:red;">*</small>
            <select name="cliente" id="adicionar-locais-clientes-text" class="form-control" >
                <option value="">Selecione uma opção</option>
                {% for cliente in context_clientes %}
                    <option value="{{cliente.id}}">Codigo: {{cliente.id}} | Nome: {{ cliente.nome_fantasia }}</option>
                {% endfor %}
            </select>
            <span class="text-danger" id="adicionar-error-locais_clientes"></span>
        </div>
    </div>
       
    <div class="modal-footer">
        <button type="button" class="btn btn-outline-danger" data-bs-dismiss="modal">Cancelar</button>
        <button type="button" class="btn btn-primary" onclick="adicionar_locais_clientes()">Confimar</button>
    </div>

{% endblock %}

website/templates/bases/alerta_erro_base.html
<div class="container_alerta" id="container_alerta_erro">   
    <div class="alerta_erro">
        <span id="alerta_mensagem_erro"></span>
        <i class="fa-solid fa-circle-exclamation" style="color: #ffffff;"></i>
    </div>
</div>

website/templates/bases/alerta_sucesso_base.html
<div class="container_alerta" id="container_alerta_sucesso">   
    <div class="alerta_sucesso">
        <span id="alerta_mensagem_sucesso"></span>
        <i class="fa-regular fa-circle-check" style="color: #ffffff;"></i>
    </div>
</div>

website/templates/bases/base.html
<!DOCTYPE html>
<html lang="pt-br">

<head>

    {% load static %}

    <meta charset="UTF-8">
    <meta name="author" content="J&C - GESTÂO DE RISCO">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="J&C, Logistica, Serviços, Gestão de Riscos, Inteligência">
    <meta name="copyright" content="© 2024 Companhia J&C Gestão de Riscos" />
    <meta http-equiv="content-language" content="pt-br, en-US, fr" />
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <meta http-equiv="pragma" content="no-cache" /> 

    <!-- Bootstrap -->
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <!-- Jquery -->
    <script type="text/javascript" src="{% static 'lib/jquery/jquery.js' %}" ></script>
    <link href="{% static 'lib/datatables/datatables.css' %}" rel="stylesheet">
    <script src="{% static 'lib/datatables/datatables.js' %}"></script>

    <!-- FontAwesomeFree Css -->
    <script src="{% static 'fontawesomefree/js/fontawesome.js' %}"></script>
    <script src="{% static 'fontawesomefree/js/solid.js' %}"></script>
    <script src="{% static 'fontawesomefree/js/regular.js' %}"></script>
    <script src="{% static 'fontawesomefree/js/brands.js' %}"></script>
       
    <!-- Css -->
    <link href="{% static 'css/siderbar.css' %}" rel="stylesheet">
    <link href="{% static 'css/global/default.css' %}" rel="stylesheet">
   
    {% block styles %}{% endblock styles %}
    <title>Controle de Iscas - {% block title %} {% endblock title %}</title>
    
</head>

<body class="body-pd" style="background-color: #F7F6FB;" id="body-pd">

    <!-- Header -->
    <header class="header body-pd" id="header">

        <div class="header_toggle bx-x" id="header-toggle"> 
            <i class="fa-solid fa-bars" ></i>
        </div>

        {% if context_usuarios %}
            <div class="header_img_content"> 
                
                <div class="header_img"> 
                    <img src="{{ context_usuarios.foto }}" alt="logado"> 
                </div>

                <h3>{{ context_usuarios.user.username }}</h3>
            </div>
        {% endif %}

    </header>

    <!-- Navbar -->
    <div class="l-navbar expansive" id="nav-bar">
        <nav class="nav">
            <article> 
                
                <div class="logo_img"> 
                  
                    
                </div>
                    
                <a href="{% url 'home' %}" class="nav_logo item-logo"> 
                    <i class="fa-solid fa-cart-flatbed-suitcase"></i>
                    <span class="nav_logo-name">Controle de Iscas</span> 
                </a>

                <hr>
                
                <div class="nav_list"> 

                    <a href="{% url 'iscas:index' %}" class="nav_link item {% if nav_isca %}active{% endif %}" data-bs-toggle="tooltip" data-bs-placement="right" title="Invetario de iscas"> 
                        <i class="fa-solid fa-box-archive"></i>
                        <span class="nav_name">Invetario de iscas</span> 
                    </a> 

                    <a href="{% url 'solicitacoes:index' %}" class="nav_link item {% if nav_solicitacao %}active{% endif %}" data-bs-toggle="tooltip" data-bs-placement="right" title="Solicitações de Check-in/out"> 
                        <i class="fa-solid fa-clipboard-check"></i>
                        <span class="nav_name">Solicitações Check-in/out</span> 
                    </a> 

                    <a href="{% url 'rastreamentos:index' %}" class="nav_link item {% if nav_rastreamento %}active{% endif %}" data-bs-toggle="tooltip" data-bs-placement="right" title="Rastreamento de iscas"> 
                        <i class="fa-solid fa-map-location-dot"></i>
                        <span class="nav_name">Rastreamentos iscas</span> 
                    </a> 
                    
                    {% if context_usuarios.roles == ROLES.ADMINISTRADOR or context_usuarios.roles == ROLES.SUPERVISOR %}
                        <a href="{% url 'locais:index' %}" class="nav_link item {% if nav_local %}active{% endif %}" data-bs-toggle="tooltip" data-bs-placement="right" title="Locais"> 
                            <i class="fa-solid fa-location-dot"></i>
                            <span class="nav_name">Locais</span> 
                        </a>
                    {% endif %}

                    
                    {% if context_usuarios.roles == ROLES.ADMINISTRADOR or context_usuarios.roles == ROLES.SUPERVISOR %}
                        <a href="{% url 'clientes:index' %}" class="nav_link item {% if nav_cliente %}active{% endif %}" data-bs-toggle="tooltip" data-bs-placement="right" title="Clientes"> 
                            <i class="fa-solid fa-users"></i>
                            <span class="nav_name">Clientes</span> 
                        </a>
                    {% endif %}

                    {% if context_usuarios.roles == ROLES.ADMINISTRADOR or context_usuarios.roles == ROLES.SUPERVISOR %}
                        <a href="{% url 'fornecedores:index' %}" class="nav_link item {% if nav_fornecedor %}active{% endif %}" data-bs-toggle="tooltip" data-bs-placement="right" title="Fornecedores"> 
                            <i class="fa-solid fa-boxes-packing"></i>
                            <span class="nav_name">Fornecedores</span> 
                        </a>
                    {% endif %}
                    
                    {% if context_usuarios.roles == ROLES.ADMINISTRADOR or context_usuarios.roles == ROLES.SUPERVISOR %}
                        <a href="{% url 'usuarios:index' %}" class="nav_link item {% if nav_usuario %}active{% endif %}" data-bs-toggle="tooltip" data-bs-placement="right" title="Usuarios"> 
                            <i class="fa-solid fa-image-portrait"></i>
                            <span class="nav_name">Usuarios</span>
                        </a> 
                    {% endif %}
             
                </div>

            </article> 
           
            <article>

                <hr>

                <a href="{% url 'logout' %}" class="nav_link item" data-bs-toggle="tooltip" data-bs-placement="right" title="Encerrar de Sessão"> 
                    <i class="fa-solid fa-arrow-right-from-bracket"></i>
                    <span class="nav_name">Encerrar Sessão</span> 
                </a>

            </article>
        </nav>
    </div>

    <!-- main -->
    <main>
        {% block conteudo %}

        {% endblock conteudo %}
    </main>
    
    <!-- Footer -->
    <footer>
        <div class="container d-flex justify-content-center align-content-center">
            <!-- <span>© 2024 Companhia&nbsp;J&amp;C Gestão de Riscos</span> -->
        </div>
    </footer>

    <!-- js -->
    <script src="{% static 'js/siderbar.js' %}"></script>
    {% block scripts %}{% endblock scripts %}
</body>

website/templates/bases/modal_base.html
{% block modal_base %}
    <div class="modal fade" id="{{modal}}_{{controller}}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="{{modal}}_{{controller}}_label" aria-hidden="true">
        
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">

            <div class="modal-content">

                <div class="modal-header">
                    {% block modal_header %}{% endblock %}
                </div>

                {% block modal_body %}{% endblock %}                  

            </div>

        </div>
        
    </div>
{% endblock %}

website/templates/bases/sub_titulo_base.html
<div class="sub-title-header">
    <a  href="{% url 'home' %}" >Home / {{request.resolver_match.namespace}} / </a>
    
    <h2>{{request.resolver_match.app_name}}</h2>
</div>